%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Dynamic Response Estimation 

% This is the main file of the dynamic response estimation algorithm. The
% algorithm is aimed for inferring the impulse response of frequency, angle
% and line powerresponse of power grid from the ambient data. In this test
% file both ambient data and impulse response data were generated by PSAT.
% The impulse response data were generated by using a step function as an
% approximation of an impulse signal to the mechanical power of a certain
% generator. The ambient data were generated by the time domain simulation
% with noise injected at all generator mechanical power. The example used
% the 2nd order model with non-uniform damping condition. The 2nd order 
% uniform damping case and higher order model cases were also validated.

% Case model: IEEE 9-bus system, 3 generators, 3 loads, 9 lines.

% Author: Shaohui Liu
% Contact: shaohui.liu@utexas.edu
% Date: Jun. 23th, 2020
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Initialize parameters and load data

% load ambient data file
% load data/TD_2nd_unif_data_power_new.mat
% load data/psat_td_data_2nd_unif.mat
load data/psat_td_data_2nd_unif_0726.mat
% load data/psat_td_data_2nd_unif_load.mat
% load data/psat_td_data_2nd_unif_load1.mat
addpath('functions');
% load data/psat_td_data_2nd_nonunif.mat
t_ambient = Varout.t;
x_ambient = Varout.vars(:,1:6);
f_ambient = Varout.vars(:,46:54);

n_gen = 3; % number of generators
n_line = 9; % number of lines
dt = .01; % discrete time step for data
T = t_ambient; % 
T_start = 20; % we use the data start from 20s

[T1,freq_data,angle_data,flow_data] = data_process(x_ambient,f_ambient,T,T_start,dt);
n1 = length(T);
n0 = length(T1);


%% Recover the dynamic response from ambient data

% frequency
freq_data = freq_data - 1;
freq_resp = frequency_response(freq_data,n_gen,dt);

% rotor angle
ang_resp = angle_response(angle_data,n_gen,dt);

% line flow
input_loc = 1;
flow_resp = line_flow_response(angle_data,flow_data,input_loc,n_gen,n_line,dt);

% inferred response of input at generator 1
freq_resp1 = freq_resp{1};
ang_resp1 = ang_resp{1};



%% Load impulse response data
% load data/impz_resp_2nd_nonunif_power.mat % impulse response w/ input@1st generator
% load data/impz_resp_2nd_unif_power.mat
load data/impz_resp_2nd_unif_power_0726.mat
% load data/impz_resp_2nd_unif_power2.mat
psat_temp = Varout;
% Time span for prediction
t_range = 5;

[freq_impz,angle_impz,flow_impz,t_psat] = psat_data_process(psat_temp,t_range,dt);

% normalization
for i = 1 : n_gen
    freq_impz(:,i) = freq_impz(:,i) ./ max(freq_impz(:,i));
end




%% Plot the results

plot_switch = 1;

T2 = 0 : dt : t_range;
plot_idx = 1 : length(T2);
if plot_switch == 1
    
% Frequency    
fig1 = figure('DefaultAxesFontSize',18);
freq_resp2 = freq_resp1(plot_idx,:);
for i = 1 : 3
    if i ~= 1
        freq_resp2(:,i) = freq_resp2(:,i) - freq_resp2(1,i);
    else
        freq_resp2(:,i) = freq_resp2(:,i) + 3e-4;
    end
    freq_resp2(:,i) = freq_resp2(:,i)./max(abs(freq_resp2(:,i)));
    subplot(1,3,i)
    plot(t_psat,freq_impz(:,i),'-.',T2,freq_resp2(plot_idx,i),'-','LineWidth',2);
    xlabel('Time [s]');
    ylabel('scale');
    xlim([0 t_range]);
    title(strcat('\omega ',num2str(i)));
    if i == 1
        legend('model based','data driven','Location','best');
    end
%     title('Input: \omega_1')
    grid on
end
sgt = sgtitle('Frequency response: 2nd order, non-uniform damping, input1');
sgt.FontSize = 32;
set(fig1,'Position',[10 10 1500 400])

% Rotor angle
fig2 = figure('DefaultAxesFontSize',18);
for i = 1 : n_gen
    subplot(1,3,i)
    plot(t_psat,angle_impz(:,i)./max(abs(angle_impz(:,i))),'-.',T2,ang_resp1(plot_idx,i) ./ -max(abs(ang_resp1(plot_idx,i))),'-','LineWidth',2); %T1,freq_resp1(:,i),'-',
    xlabel('Time [s]');
    ylabel('scale');
    xlim([0 t_range]);
    title(strcat('\delta ',num2str(i)));
    if i == 1
        legend('model based','data driven','Location','best');
    end
%     title('Input: \omega_1')
    grid on
end
sgt = sgtitle('Rotor angle response: 2nd order, non-uniform damping, input1 ');
sgt.FontSize = 32;
set(fig2,'Position',[10 200 1500 400])

% Line flow
fig3 = figure('DefaultAxesFontSize',18);
line_idx = ["9-8", "7-8", "9-6", "7-5", "5-4", "6-4", "2-7", "3-9", "1-4"];
flow_impz1 = flow_impz .* .1; % power rating
for i  = 1 : n_line
    subplot(3,3,i)
    flow_resp_temp = - (flow_resp(plot_idx,i)-flow_resp(plot_idx(1),i));
    flow_resp_temp = flow_resp_temp ./ 73;
    flow_impz_temp = flow_impz1(:,i)-flow_impz1(1,i);
    plot(t_psat,flow_impz_temp ./ max(abs(flow_impz_temp)),'-.',T2,flow_resp_temp ./ max(abs(flow_resp_temp)),'-','LineWidth',2);
    xlabel('Time [s]');
    ylabel('Power dev. [MW]');
    xlim([0 t_range]);
    title(strcat('line ',line_idx(i)));
    if i == 1
        legend('model based','data driven','Location','best');
    end
%     title('Input: \omega_2')
    grid on
end
sgt = sgtitle('Line response: 2nd order, non-uniform damping, input1');
sgt.FontSize = 32;
set(fig3,'Position',[10 500 1500 1200])
    
end



